### ISSUE TITLE
生成二维码报错

### ISSUE THREAD

**Issue by xuyuan3** [wangrongding/wechat-bot#150]
`11:04:49 ERR PuppetWeChatBridge start() exception: Error: net::ERR_CONNECTION_RESET at https://wx.qq.com?lang=zh_CN&target=t
11:04:49 ERR PuppetWeChat initBridge() exception: net::ERR_CONNECTION_RESET at https://wx.qq.com?lang=zh_CN&target=t
11:04:49 WARN PuppetWeChatBridge stop() page.close() exception: Error: Protocol error: Connection closed. Most likely the page has been closed.
GError: net::ERR_CONNECTION_RESET at https://wx.qq.com?lang=zh_CN&target=t
    at navigate (/Users/didi/Desktop/wechat-bot-main/node_modules/puppeteer/lib/cjs/puppeteer/common/FrameManager.js:156:23)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async FrameManager.navigateFrame (/Users/didi/Desktop/wechat-bot-main/node_modules/puppeteer/lib/cjs/puppeteer/common/FrameManager.js:131:21)
    at async Frame.goto (/Users/didi/Desktop/wechat-bot-main/node_modules/puppeteer/lib/cjs/puppeteer/common/FrameManager.js:512:16)
    at async Page.goto (/Users/didi/Desktop/wechat-bot-main/node_modules/puppeteer/lib/cjs/puppeteer/common/Page.js:1167:16)
    at async Bridge.initPage (file:///Users/didi/Desktop/wechat-bot-main/node_modules/wechaty-puppet-wechat/dist/esm/src/bridge.js:181:9)
    at async Bridge.start (file:///Users/didi/Desktop/wechat-bot-main/node_modules/wechaty-puppet-wechat/dist/esm/src/bridge.js:52:25)
    at async PuppetWeChat.initBridge (file:///Users/didi/Desktop/wechat-bot-main/node_modules/wechaty-puppet-wechat/dist/esm/src/puppet-wechat.js:176:13)
    at async PuppetWeChat.onStart (file:///Users/didi/Desktop/wechat-bot-main/node_modules/wechaty-puppet-wechat/dist/esm/src/puppet-wechat.js:69:23)
    at async PuppetWeChat.start (file:///Users/didi/Desktop/wechat-bot-main/node_modules/wechaty-puppet/node_modules/state-switch/dist/esm/src/service-ctl/service-ctl.js:62:17) {
  code: 2,
  details: 'Error: net::ERR_CONNECTION_RESET at https://wx.qq.com?lang=zh_CN&target=t\n' +
    '    at navigate (/Users/didi/Desktop/wechat-bot-main/node_modules/puppeteer/lib/cjs/puppeteer/common/FrameManager.js:156:23)\n' +
    '    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n' +
    '    at async FrameManager.navigateFrame (/Users/didi/Desktop/wechat-bot-main/node_modules/puppeteer/lib/cjs/puppeteer/common/FrameManager.js:131:21)\n' +
    '    at async Frame.goto (/Users/didi/Desktop/wechat-bot-main/node_modules/puppeteer/lib/cjs/puppeteer/common/FrameManager.js:512:16)\n' +
    '    at async Page.goto (/Users/didi/Desktop/wechat-bot-main/node_modules/puppeteer/lib/cjs/puppeteer/common/Page.js:1167:16)\n' +
    '    at async Bridge.initPage (file:///Users/didi/Desktop/wechat-bot-main/node_modules/wechaty-puppet-wechat/dist/esm/src/bridge.js:181:9)\n' +
    '    at async Bridge.start (file:///Users/didi/Desktop/wechat-bot-main/node_modules/wechaty-puppet-wechat/dist/esm/src/bridge.js:52:25)\n' +
    '    at async PuppetWeChat.initBridge (file:///Users/didi/Desktop/wechat-bot-main/node_modules/wechaty-puppet-wechat/dist/esm/src/puppet-wechat.js:176:13)\n' +
    '    at async PuppetWeChat.onStart (file:///Users/didi/Desktop/wechat-bot-main/node_modules/wechaty-puppet-wechat/dist/esm/src/puppet-wechat.js:69:23)\n' +
    '    at async PuppetWeChat.start (file:///Users/didi/Desktop/wechat-bot-main/node_modules/wechaty-puppet/node_modules/state-switch/dist/esm/src/service-ctl/service-ctl.js:62:17)'
}`

**Comment by xuyuan3** [comment]
`11:04:49 ERR PuppetWeChatBridge start() exception: Error: net::ERR_CONNECTION_RESET at https://wx.qq.com?lang=zh_CN&target=t
11:04:49 ERR PuppetWeChat initBridge() exception: net::ERR_CONNECTION_RESET at https://wx.qq.com?lang=zh_CN&target=t
11:04:49 WARN PuppetWeChatBridge stop() page.close() exception: Error: Protocol error: Connection closed. Most likely the page has been closed.
GError: net::ERR_CONNECTION_RESET at https://wx.qq.com?lang=zh_CN&target=t
    at navigate (/Users/didi/Desktop/wechat-bot-main/node_modules/puppeteer/lib/cjs/puppeteer/common/FrameManager.js:156:23)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async FrameManager.navigateFrame (/Users/didi/Desktop/wechat-bot-main/node_modules/puppeteer/lib/cjs/puppeteer/common/FrameManager.js:131:21)
    at async Frame.goto (/Users/didi/Desktop/wechat-bot-main/node_modules/puppeteer/lib/cjs/puppeteer/common/FrameManager.js:512:16)
    at async Page.goto (/Users/didi/Desktop/wechat-bot-main/node_modules/puppeteer/lib/cjs/puppeteer/common/Page.js:1167:16)
    at async Bridge.initPage (file:///Users/didi/Desktop/wechat-bot-main/node_modules/wechaty-puppet-wechat/dist/esm/src/bridge.js:181:9)
    at async Bridge.start (file:///Users/didi/Desktop/wechat-bot-main/node_modules/wechaty-puppet-wechat/dist/esm/src/bridge.js:52:25)
    at async PuppetWeChat.initBridge (file:///Users/didi/Desktop/wechat-bot-main/node_modules/wechaty-puppet-wechat/dist/esm/src/puppet-wechat.js:176:13)
    at async PuppetWeChat.onStart (file:///Users/didi/Desktop/wechat-bot-main/node_modules/wechaty-puppet-wechat/dist/esm/src/puppet-wechat.js:69:23)
    at async PuppetWeChat.start (file:///Users/didi/Desktop/wechat-bot-main/node_modules/wechaty-puppet/node_modules/state-switch/dist/esm/src/service-ctl/service-ctl.js:62:17) {
  code: 2,
  details: 'Error: net::ERR_CONNECTION_RESET at https://wx.qq.com?lang=zh_CN&target=t\n' +
    '    at navigate (/Users/didi/Desktop/wechat-bot-main/node_modules/puppeteer/lib/cjs/puppeteer/common/FrameManager.js:156:23)\n' +
    '    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n' +
    '    at async FrameManager.navigateFrame (/Users/didi/Desktop/wechat-bot-main/node_modules/puppeteer/lib/cjs/puppeteer/common/FrameManager.js:131:21)\n' +
    '    at async Frame.goto (/Users/didi/Desktop/wechat-bot-main/node_modules/puppeteer/lib/cjs/puppeteer/common/FrameManager.js:512:16)\n' +
    '    at async Page.goto (/Users/didi/Desktop/wechat-bot-main/node_modules/puppeteer/lib/cjs/puppeteer/common/Page.js:1167:16)\n' +
    '    at async Bridge.initPage (file:///Users/didi/Desktop/wechat-bot-main/node_modules/wechaty-puppet-wechat/dist/esm/src/bridge.js:181:9)\n' +
    '    at async Bridge.start (file:///Users/didi/Desktop/wechat-bot-main/node_modules/wechaty-puppet-wechat/dist/esm/src/bridge.js:52:25)\n' +
    '    at async PuppetWeChat.initBridge (file:///Users/didi/Desktop/wechat-bot-main/node_modules/wechaty-puppet-wechat/dist/esm/src/puppet-wechat.js:176:13)\n' +
    '    at async PuppetWeChat.onStart (file:///Users/didi/Desktop/wechat-bot-main/node_modules/wechaty-puppet-wechat/dist/esm/src/puppet-wechat.js:69:23)\n' +
    '    at async PuppetWeChat.start (file:///Users/didi/Desktop/wechat-bot-main/node_modules/wechaty-puppet/node_modules/state-switch/dist/esm/src/service-ctl/service-ctl.js:62:17)'
}`
