### ISSUE TITLE
bot error❌:  GError: Parse Error: Invalid status code

### ISSUE THREAD

**Issue by bochennn** [wangrongding/wechat-bot#165]
我给我自己发没问题，别人给我发就报下面的错

![20240407-224053](https://github.com/wangrongding/wechat-bot/assets/17314925/b48e9127-b16e-4dc5-b8ee-3f109c4cbb78)

**Comment by xiaobujun** [comment]
遇到了相似的问题，但我的是报502
![1](https://github.com/wangrongding/wechat-bot/assets/73051552/6d1ee199-b77a-480d-8d6e-dd011b74d840)

**Comment by yanglgtm** [comment]
+1, 启动后，没有发送消息，过一会就自动就弹出这个错误。

**Comment by wangrongding** [comment]
选的哪个ai服务？

**Comment by xiaobujun** [comment]
> 选的哪个ai服务？

Kimi

**Comment by bochennn** [comment]
> 选的哪个ai服务？

我也是kimi

**Comment by yanglgtm** [comment]
我用的 chatgtp

**Comment by jiaxinonly** [comment]
感觉跟微信状态有关，保持手机上微信分身前台运行，没有问题，一当打开主微信，发送消息，就报错，估计分身上微信离线了

**Comment by newTechAccount** [comment]
我这边是这样的
bot error?:  GError [AggregateError]
    at AxiosError.from (/root/wechat-bot/node_modules/axios/dist/node/axios.cjs:841:14)
    at RedirectableRequest.handleRequestError (/root/wechat-bot/node_modules/axios/dist/node/axios.cjs:3106:25)
    at RedirectableRequest.emit (node:events:531:35)
    at eventHandlers.<computed> (/root/wechat-bot/node_modules/follow-redirects/index.js:38:24)
    at ClientRequest.emit (node:events:519:28)
    at TLSSocket.socketErrorListener (node:_http_client:500:9)
    at TLSSocket.emit (node:events:519:28)
    at emitErrorNT (node:internal/streams/destroy:169:8)
    at emitErrorCloseNT (node:internal/streams/destroy:128:3)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)
    at Axios.request (/root/wechat-bot/node_modules/axios/dist/node/axios.cjs:4224:41)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
  code: 2,
  details: 'AggregateError\n' +
    '    at AxiosError.from (/root/wechat-bot/node_modules/axios/dist/node/axios.cjs:841:14)\n' +
    '    at RedirectableRequest.handleRequestError (/root/wechat-bot/node_modules/axios/dist/node/axios.cjs:3106:25)\n' +
    '    at RedirectableRequest.emit (node:events:531:35)\n' +
    '    at eventHandlers.<computed> (/root/wechat-bot/node_modules/follow-redirects/index.js:38:24)\n' +
    '    at ClientRequest.emit (node:events:519:28)\n' +
    '    at TLSSocket.socketErrorListener (node:_http_client:500:9)\n' +
    '    at TLSSocket.emit (node:events:519:28)\n' +
    '    at emitErrorNT (node:internal/streams/destroy:169:8)\n' +
    '    at emitErrorCloseNT (node:internal/streams/destroy:128:3)\n' +
    '    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)\n' +
    '    at Axios.request (/root/wechat-bot/node_modules/axios/dist/node/axios.cjs:4224:41)\n' +
    '    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)'
}
? 程序退出,请重新运行程序

**Comment by newTechAccount** [comment]
> 感觉跟微信状态有关，保持手机上微信分身前台运行，没有问题，一当打开主微信，发送消息，就报错，估计分身上微信离线了

没看懂，主微信不就是手机上的吗？

**Comment by jiaxinonly** [comment]
> > 感觉跟微信状态有关，保持手机上微信分身前台运行，没有问题，一当打开主微信，发送消息，就报错，估计分身上微信离线了
> 
> 没看懂，主微信不就是手机上的吗？

我是小号用的微信分身
