### ISSUE TITLE
成功登录，但是会报错

### ISSUE THREAD

**Issue by LAOZTK** [wangrongding/wechat-bot#178]
Current time:Wed May 29 2024 11:24:20 GMT+0800 (中国标准时间)
Automatic robot chat mode has been activated
bot error❌:  AssertionError [ERR_ASSERTION]: -1 == 0
    at Object.equal (D:\wechat-bot-main\node_modules\wechat4u\lib\util\global.js:69:24)
    at D:\wechat-bot-main\node_modules\wechat4u\lib\core.js:326:24
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Promise.all (index 1) {
  code: 2,
  details: 'AssertionError [ERR_ASSERTION]: -1 == 0\n' +
    '    at Object.equal (D:\\wechat-bot-main\\node_modules\\wechat4u\\lib\\util\\global.js:69:24)\n' +
    '    at D:\\wechat-bot-main\\node_modules\\wechat4u\\lib\\core.js:326:24\n' +
    '    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n' +
    '    at async Promise.all (index 1)'
}
❌ 程序退出,请重新运行程序

**Comment by LAOZTK** [comment]
上面的错误是最新的代码出现的

切换到release的版本 可以登录，但是会出现
uncaughtException AssertionError [ERR_ASSERTION]: -1 == 0
    at Object.equal (D:\wechat-bot-0.0.2\node_modules\wechat4u\lib\util\global.js:69:24)
    at D:\wechat-bot-0.0.2\node_modules\wechat4u\lib\core.js:326:24
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Promise.all (index 1) {
  code: 2,
  details: 'AssertionError [ERR_ASSERTION]: -1 == 0\n' +
    '    at Object.equal (D:\\wechat-bot-0.0.2\\node_modules\\wechat4u\\lib\\util\\global.js:69:24)\n' +
    '    at D:\\wechat-bot-0.0.2\\node_modules\\wechat4u\\lib\\core.js:326:24\n' +
    '    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n' +
    '    at async Promise.all (index 1)'
}
uncaughtException AssertionError [ERR_ASSERTION]: -1 == 0
    at Object.equal (D:\wechat-bot-0.0.2\node_modules\wechat4u\lib\util\global.js:69:24)
    at D:\wechat-bot-0.0.2\node_modules\wechat4u\lib\core.js:326:24
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Promise.all (index 1) {
  code: 2,
  details: 'AssertionError [ERR_ASSERTION]: -1 == 0\n' +
    '    at Object.equal (D:\\wechat-bot-0.0.2\\node_modules\\wechat4u\\lib\\util\\global.js:69:24)\n' +
    '    at D:\\wechat-bot-0.0.2\\node_modules\\wechat4u\\lib\\core.js:326:24\n' +
    '    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n' +
    '    at async Promise.all (index 1)'
}

**Comment by fuuuc** [comment]
请问解决了吗

**Comment by LinHanlove** [comment]
解决了吗
