### ISSUE TITLE
跑一会就会跳出，不知道什么原因

### ISSUE THREAD

**Issue by newTechAccount** [wangrongding/wechat-bot#186]
bot error?:  GError [AggregateError]
    at AxiosError.from (/root/wechat-bot/node_modules/axios/dist/node/axios.cjs:841:14)
    at RedirectableRequest.handleRequestError (/root/wechat-bot/node_modules/axios/dist/node/axios.cjs:3106:25)
    at RedirectableRequest.emit (node:events:531:35)
    at eventHandlers.<computed> (/root/wechat-bot/node_modules/follow-redirects/index.js:38:24)
    at ClientRequest.emit (node:events:519:28)
    at TLSSocket.socketErrorListener (node:_http_client:500:9)
    at TLSSocket.emit (node:events:519:28)
    at emitErrorNT (node:internal/streams/destroy:169:8)
    at emitErrorCloseNT (node:internal/streams/destroy:128:3)
    at processTicksAndRejections (node:internal/process/task_queues:82:21)
    at Axios.request (/root/wechat-bot/node_modules/axios/dist/node/axios.cjs:4224:41)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at runNextTicks (node:internal/process/task_queues:64:3)
    at process.processTimers (node:internal/timers:511:9) {
  code: 2,
  details: 'AggregateError\n' +
    '    at AxiosError.from (/root/wechat-bot/node_modules/axios/dist/node/axios.cjs:841:14)\n' +
    '    at RedirectableRequest.handleRequestError (/root/wechat-bot/node_modules/axios/dist/node/axios.cjs:3106:25)\n' +
    '    at RedirectableRequest.emit (node:events:531:35)\n' +
    '    at eventHandlers.<computed> (/root/wechat-bot/node_modules/follow-redirects/index.js:38:24)\n' +
    '    at ClientRequest.emit (node:events:519:28)\n' +
    '    at TLSSocket.socketErrorListener (node:_http_client:500:9)\n' +
    '    at TLSSocket.emit (node:events:519:28)\n' +
    '    at emitErrorNT (node:internal/streams/destroy:169:8)\n' +
    '    at emitErrorCloseNT (node:internal/streams/destroy:128:3)\n' +
    '    at processTicksAndRejections (node:internal/process/task_queues:82:21)\n' +
    '    at Axios.request (/root/wechat-bot/node_modules/axios/dist/node/axios.cjs:4224:41)\n' +
    '    at processTicksAndRejections (node:internal/process/task_queues:95:5)\n' +
    '    at runNextTicks (node:internal/process/task_queues:64:3)\n' +
    '    at process.processTimers (node:internal/timers:511:9)'
}
? 程序退出,请重新运行程序

**Comment by newTechAccount** [comment]
bot error?:  GError [AxiosError]: Request failed with status code 503
    at settle (/root/wechat-bot/node_modules/axios/dist/node/axios.cjs:1983:12)
    at IncomingMessage.handleStreamEnd (/root/wechat-bot/node_modules/axios/dist/node/axios.cjs:3085:11)
    at IncomingMessage.emit (node:events:531:35)
    at endReadableNT (node:internal/streams/readable:1696:12)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)
    at Axios.request (/root/wechat-bot/node_modules/axios/dist/node/axios.cjs:4224:41)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Promise.all (index 1) {
  code: 2,
  details: 'AxiosError: Request failed with status code 503\n' +
    '    at settle (/root/wechat-bot/node_modules/axios/dist/node/axios.cjs:1983:12)\n' +
    '    at IncomingMessage.handleStreamEnd (/root/wechat-bot/node_modules/axios/dist/node/axios.cjs:3085:11)\n' +
    '    at IncomingMessage.emit (node:events:531:35)\n' +
    '    at endReadableNT (node:internal/streams/readable:1696:12)\n' +
    '    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)\n' +
    '    at Axios.request (/root/wechat-bot/node_modules/axios/dist/node/axios.cjs:4224:41)\n' +
    '    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n' +
    '    at async Promise.all (index 1)'
}
? 程序退出,请重新运行程序

**Comment by wangrongding** [comment]
重新拉取最新代码即可

**Comment by mengxi-ream** [comment]
我也有这个报错，最新的代码
