### ISSUE TITLE
docker部署运行约两天后报错停止

### ISSUE THREAD

**Issue by sd3420625** [wangrongding/wechat-bot#190]
ubuntu22系统，新版代码，docker部署约40小时后log显示报错（此问题老版本程序也存在），具体如下：

❌ bot error handle:  GError: 连续167次同步失败，5s后尝试重启
    at /app/node_modules/wechat4u/lib/wechat.js:129:22
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
  code: 2,
  details: 'Error: 连续167次同步失败，5s后尝试重启\n' +
    '    at /app/node_modules/wechat4u/lib/wechat.js:129:22\n' +
    '    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)'
}
❌ uncaughtException 捕获到未处理的异常:  Error: must logout first before login again!
    at PuppetWechat4u.login (file:///app/node_modules/wechaty-puppet/dist/esm/src/mixins/login-mixin.js:81:23)
    at Wechat.<anonymous> (file:///app/node_modules/wechaty-puppet-wechat4u/dist/esm/src/puppet-wechat4u.js:289:24)
    at Wechat.emit (node:events:513:28)
    at /app/node_modules/wechat4u/lib/wechat.js:202:16
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
uncaughtException Error: must logout first before login again!
    at PuppetWechat4u.login (file:///app/node_modules/wechaty-puppet/dist/esm/src/mixins/login-mixin.js:81:23)
    at Wechat.<anonymous> (file:///app/node_modules/wechaty-puppet-wechat4u/dist/esm/src/puppet-wechat4u.js:289:24)
    at Wechat.emit (node:events:513:28)
    at /app/node_modules/wechat4u/lib/wechat.js:202:16
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
❌ bot error handle:  AssertionError [ERR_ASSERTION]: 1205 == 0
    at Object.equal (/app/node_modules/wechat4u/lib/util/global.js:69:24)
    at /app/node_modules/wechat4u/lib/core.js:265:24
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
  code: 2,
  details: 'AssertionError [ERR_ASSERTION]: 1205 == 0\n' +
    '    at Object.equal (/app/node_modules/wechat4u/lib/util/global.js:69:24)\n' +
    '    at /app/node_modules/wechat4u/lib/core.js:265:24\n' +
    '    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)'
}
❌ bot error handle:  AssertionError [ERR_ASSERTION]: 1205 == 0
    at Object.equal (/app/node_modules/wechat4u/lib/util/global.js:69:24)
    at /app/node_modules/wechat4u/lib/core.js:265:24
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
  code: 2,
  details: 'AssertionError [ERR_ASSERTION]: 1205 == 0\n' +
    '    at Object.equal (/app/node_modules/wechat4u/lib/util/global.js:69:24)\n' +
    '    at /app/node_modules/wechat4u/lib/core.js:265:24\n' +
    '    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)'
}
❌ bot error handle:  AssertionError [ERR_ASSERTION]: 3 == 0
    at Object.equal (/app/node_modules/wechat4u/lib/util/global.js:69:24)
    at /app/node_modules/wechat4u/lib/core.js:446:24
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
  code: 2,
  details: 'AssertionError [ERR_ASSERTION]: 3 == 0\n' +
    '    at Object.equal (/app/node_modules/wechat4u/lib/util/global.js:69:24)\n' +
    '    at /app/node_modules/wechat4u/lib/core.js:446:24\n' +
    '    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)'

荣大方便时候看看

**Comment by sd3420625** [comment]
这个问题可以复现，只不过耗时较长

**Comment by lengsukq** [comment]
我也碰到了，猜测微信风控了，然后token失效需要重新登录

**Comment by sd3420625** [comment]
好的，谢谢，那就没办法了

**Comment by lengsukq** [comment]
> 好的，谢谢，那就没办法了

可以看一下我仓库的代码，新增了邮件提醒，报错了会发邮件给你提醒你重新登录，重新登录的二维码也是直接发到你邮箱的，直接扫码登录就可以了。
