### ISSUE TITLE
登陆之后自动回复出现503报错

### ISSUE THREAD

**Issue by AkoZhu** [wangrongding/wechat-bot#192]
```
❌ bot error handle:  GError [AxiosError]: Request failed with status code 503
    at settle (/data/workspace/repo/wechat-bot/node_modules/axios/dist/node/axios.cjs:1983:12)
    at IncomingMessage.handleStreamEnd (/data/workspace/repo/wechat-bot/node_modules/axios/dist/node/axios.cjs:3085:11)
    at IncomingMessage.emit (node:events:526:35)
    at endReadableNT (node:internal/streams/readable:1359:12)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)
    at Axios.request (/data/workspace/repo/wechat-bot/node_modules/axios/dist/node/axios.cjs:4224:41)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Promise.all (index 0) {
  code: 2,
  details: 'AxiosError: Request failed with status code 503\n' +
    '    at settle (/data/workspace/repo/wechat-bot/node_modules/axios/dist/node/axios.cjs:1983:12)\n' +
    '    at IncomingMessage.handleStreamEnd (/data/workspace/repo/wechat-bot/node_modules/axios/dist/node/axios.cjs:3085:11)\n' +
    '    at IncomingMessage.emit (node:events:526:35)\n' +
    '    at endReadableNT (node:internal/streams/readable:1359:12)\n' +
    '    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)\n' +
    '    at Axios.request (/data/workspace/repo/wechat-bot/node_modules/axios/dist/node/axios.cjs:4224:41)\n' +
    '    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n' +
    '    at async Promise.all (index 0)'
}
```

看起来是 `wechaty-puppet-wechat4u` 有点问题。。环境是CentOs + node.js@v18.17.0.不知道有没有解决办法

**Comment by AkoZhu** [comment]
解决了。不能给自己发信息 :)
