### ISSUE TITLE
npm run dev后扫描二维码报错：bot error handle:  AssertionError [ERR_ASSERTION]: 1 == 0

### ISSUE THREAD

**Issue by TangyiCao** [wangrongding/wechat-bot#202]
INFO onScan: 3(undefined) Scanned
❌ bot error handle:  AssertionError [ERR_ASSERTION]: 1 == 0
    at Object.equal (C:\Users\Administrator\Desktop\wechat-bot-main\node_modules\wechat4u\lib\util\global.js:69:24)
    at C:\Users\Administrator\Desktop\wechat-bot-main\node_modules\wechat4u\lib\core.js:229:24
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
  code: 2,
  details: 'AssertionError [ERR_ASSERTION]: 1 == 0\n' +
    '    at Object.equal (C:\\Users\\Administrator\\Desktop\\wechat-bot-main\\node_modules\\wechat4u\\lib\\util\\global.js:69:24)\n' +
    '    at C:\\Users\\Administrator\\Desktop\\wechat-bot-main\\node_modules\\wechat4u\\lib\\core.js:229:24\n' +
    '    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)'
}

**Comment by TangyiCao** [comment]
问题已解决，因为用的是小号，没有实名认证所以无法登陆。认证后登录成功且能正常使用自动回复功能了
![Uploading image.png…]()
