### ISSUE TITLE
运行一段时间后，控制台提示：bot error handle:  GError [AxiosError]: timeout of 60000ms exceeded   ，但是还是能回复消息，很奇怪。

### ISSUE THREAD

**Issue by TangyiCao** [wangrongding/wechat-bot#203]
bot error handle:  GError [AxiosError]: timeout of 60000ms exceeded                                                                          
    at RedirectableRequest.handleRequestTimeout (C:\Users\Administrator\Desktop\wechat-bot-main\node_modules\axios\dist\node\axios.cjs:3143:16)
    at RedirectableRequest.emit (node:events:517:28)
    at Timeout.<anonymous> (C:\Users\Administrator\Desktop\wechat-bot-main\node_modules\follow-redirects\index.js:210:12)
    at listOnTimeout (node:internal/timers:569:17)
    at process.processTimers (node:internal/timers:512:7)
    at Axios.request (C:\Users\Administrator\Desktop\wechat-bot-main\node_modules\axios\dist\node\axios.cjs:4224:41) {
  code: 2,
  details: 'AxiosError: timeout of 60000ms exceeded\n' +
    '    at RedirectableRequest.handleRequestTimeout (C:\\Users\\Administrator\\Desktop\\wechat-bot-main\\node_modules\\axios\\dist\\node\\axios.cjs:3143:16)\n' 
+
    '    at RedirectableRequest.emit (node:events:517:28)\n' +
    '    at Timeout.<anonymous> (C:\\Users\\Administrator\\Desktop\\wechat-bot-main\\node_modules\\follow-redirects\\index.js:210:12)\n' +
    '    at listOnTimeout (node:internal/timers:569:17)\n' +
    '    at process.processTimers (node:internal/timers:512:7)\n' +
    '    at Axios.request (C:\\Users\\Administrator\\Desktop\\wechat-bot-main\\node_modules\\axios\\dist\\node\\axios.cjs:4224:41)'
}

**Comment by wangrongding** [comment]
说明某次请求超时了，后续的请求正常
