### ISSUE TITLE
WARN PuppetWechat4u contactRawPayload(AssertionError [ERR_ASSERTION]: 1205 == 0) wechat4u.batchGetContact() 

### ISSUE THREAD

**Issue by hiddenlong** [wangrongding/wechat-bot#205]
Automatic robot chat mode has been activated
16:51:57 WARN PuppetWechat4u contactRawPayload(AssertionError [ERR_ASSERTION]: 1205 == 0) wechat4u.batchGetContact() exception: undefined
❌ bot error handle:  AssertionError [ERR_ASSERTION]: 1205 == 0
    at Object.equal (F:\AI.Workspaces\wechat-bot-main\node_modules\wechat4u\lib\util\global.js:69:24)
    at F:\AI.Workspaces\wechat-bot-main\node_modules\wechat4u\lib\core.js:326:24
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Promise.all (index 1) {
  code: 2,
  details: 'AssertionError [ERR_ASSERTION]: 1205 == 0\n' +
    '    at Object.equal (F:\\AI.Workspaces\\wechat-bot-main\\node_modules\\wechat4u\\lib\\util\\global.js:69:24)\n' +
    '    at F:\\AI.Workspaces\\wechat-bot-main\\node_modules\\wechat4u\\lib\\core.js:326:24\n' +
    '    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n' +
    '    at async Promise.all (index 1)'
}
16:51:59 WARN PuppetWechat4u contactRawPayload(AssertionError [ERR_ASSERTION]: 1205 == 0) wechat4u.batchGetContact() exception: undefined
❌ bot error handle:  AssertionError [ERR_ASSERTION]: 1205 == 0
    at Object.equal (F:\AI.Workspaces\wechat-bot-main\node_modules\wechat4u\lib\util\global.js:69:24)
    at F:\AI.Workspaces\wechat-bot-main\node_modules\wechat4u\lib\core.js:326:24
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Promise.all (index 0) {
  code: 2,
  details: 'AssertionError [ERR_ASSERTION]: 1205 == 0\n' +
    '    at Object.equal (F:\\AI.Workspaces\\wechat-bot-main\\node_modules\\wechat4u\\lib\\util\\global.js:69:24)\n' +
    '    at F:\\AI.Workspaces\\wechat-bot-main\\node_modules\\wechat4u\\lib\\core.js:326:24\n' +
    '    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n' +
    '    at async Promise.all (index 0)'
}
16:52:01 WARN PuppetWechat4u contactRawPayload(AssertionError [ERR_ASSERTION]: 1205 == 0) wechat4u.batchGetContact() exception: undefined
16:52:03 WARN PuppetWechat4u contactRawPayload(AssertionError [ERR_ASSERTION]: 1205 == 0) wechat4u.batchGetContact() exception: undefined
❌ bot error handle:  AssertionError [ERR_ASSERTION]: 1205 == 0
    at Object.equal (F:\AI.Workspaces\wechat-bot-main\node_modules\wechat4u\lib\util\global.js:69:24)
    at F:\AI.Workspaces\wechat-bot-main\node_modules\wechat4u\lib\core.js:326:24
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
  code: 2,
  details: 'AssertionError [ERR_ASSERTION]: 1205 == 0\n' +
    '    at Object.equal (F:\\AI.Workspaces\\wechat-bot-main\\node_modules\\wechat4u\\lib\\util\\global.js:69:24)\n' +
    '    at F:\\AI.Workspaces\\wechat-bot-main\\node_modules\\wechat4u\\lib\\core.js:326:24\n' +
    '    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)'
}
16:52:05 WARN PuppetWechat4u contactRawPayload(AssertionError [ERR_ASSERTION]: 1205 == 0) wechat4u.batchGetContact() exception: undefined
16:52:07 WARN PuppetWechat4u contactRawPayload(AssertionError [ERR_ASSERTION]: 1205 == 0) wechat4u.batchGetContact() exception: undefined
16:52:09 WARN PuppetWechat4u contactRawPayload(AssertionError [ERR_ASSERTION]: 1205 == 0) wechat4u.batchGetContact() exception: undefined

**Comment by lfcleo** [comment]
我也出现这个了，但还能使用，就是控制台一直输出这个
