### ISSUE TITLE
Automatic robot chat mode has been activated

### ISSUE THREAD

**Issue by hudikiller** [wangrongding/wechat-bot#241]
bot error: AssertionError [ERR_ASSERTION]: 400 != 400
    at Object.notEqual (/mnt/d/hd/bitai/wechat-bot/node_modules/wechat4u/lib/util/global.js:79:24)
    at /mnt/d/hd/bitai/wechat-bot/node_modules/wechat4u/lib/core.js:139:24
    at process.processTicksAndRejections (node:internal/process/task_queues:105:5) {
  code: 2,
  details: 'AssertionError [ERR_ASSERTION]: 400 != 400\n' +
    '    at Object.notEqual (/mnt/d/hd/bitai/wechat-bot/node_modules/wechat4u/lib/util/global.js:79:24)\n' +
    '    at /mnt/d/hd/bitai/wechat-bot/node_modules/wechat4u/lib/core.js:139:24\n' +
    '    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)'
}

**Comment by kkpo4553** [comment]
Hello, we tried to solve the issue.

This is what we did:

Updated the error handling in the bot.on('error') event to specifically catch and handle the AssertionError. Added a retry mechanism for bot startup and improved logging for better debugging.

You can review changes in this commit: https://github.com/kkpo4553/wangrongding-wechat-bot-241/commit/bef54a0a79225aacef28ae9af2730667fb65b8ba.


> [!CAUTION]
> Disclaimer: The concept of solution was created by AI and you should never copy paste this code before you check the correctness of generated code. Solution might not be complete, you should use this code as an inspiration only.

---

If you no longer want Latta AI to attempt solving issues on your repository, you can block this account.

**Comment by laoba3** [comment]
哥们你解决了吗？
