### ISSUE TITLE
使用apikey 报错 Request failed with status code 400

### ISSUE THREAD

**Issue by 912988434** [wangrongding/wechat-bot#42]
如下
🚀🚀🚀 / prompt dkada
Error: Request failed with status code 400
    at createError (/Users/ls/Downloads/wechat-chatgpt/wechat-bot/node_modules/openai/node_modules/axios/lib/core/createError.js:16:15)
    at settle (/Users/ls/Downloads/wechat-chatgpt/wechat-bot/node_modules/openai/node_modules/axios/lib/core/settle.js:17:12)
    at IncomingMessage.handleStreamEnd (/Users/ls/Downloads/wechat-chatgpt/wechat-bot/node_modules/openai/node_modules/axios/lib/adapters/http.js:322:11)
    at IncomingMessage.emit (node:events:539:35)
    at endReadableNT (node:internal/streams/readable:1344:12)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21) {

**Comment by udbyygyt** [comment]
我也遇到了，好像长一点的提问就会报这个错

**Comment by pqshao** [comment]
我也遇到了啊，有人解决了吗？不会自动回复，也有这个报错

**Comment by pqshao** [comment]
@912988434 你后来怎么解决的？

**Comment by 912988434** [comment]
@pqshao  没用这个了，微信有几率封号，我当时就被封了三天
