### ISSUE TITLE
ERR PuppetWeChat messageSendText() exception: cannot say nothing :

### ISSUE THREAD

**Issue by surest-sky** [wangrongding/wechat-bot#71]
🚀🚀🚀 / prompt 给我写一串代码
🚀🚀🚀 / reply \#include \<stdio.h>
int main(){
int a=5;
int b=7;
int c=a+b;
printf("%d + %d = %d",a,b,c);
return 0;
}

🚀🚀🚀 / prompt 用php写一个递归脚本
🚀🚀🚀 / reply
11:45:08 ERR PuppetWeChat messageSendText() exception: cannot say nothing
Error: cannot say nothing
    at Bridge.send (file:///Users/surest/www/project/wechat-bot/node_modules/wechaty-puppet-wechat/dist/esm/src/bridge.js:445:19)
    at PuppetWeChat.messageSendText (file:///Users/surest/www/project/wechat-bot/node_modules/wechaty-puppet-wechat/dist/esm/src/puppet-wechat.js:341:31)
    at file:///Users/surest/www/project/wechat-bot/node_modules/wechaty/dist/esm/src/sayable/deliver-sayable.js:12:23
    at WechatifiedUserClass.say (file:///Users/surest/www/project/wechat-bot/node_modules/wechaty/dist/esm/src/user-modules/contact.js:274:91)
    at defaultMessage (file:///Users/surest/www/project/wechat-bot/src/wechaty/sendMessage.js:34:23)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async WechatyImpl.onMessage (file:///Users/surest/www/project/wechat-bot/src/wechaty/index.js:47:3)

**Comment by surest-sky** [comment]
好像正常使用是没问题的，但是一旦要他写代码，就有问题了
<img width="1020" alt="image" src="https://user-images.githubusercontent.com/29169847/208017475-fa33c782-f826-4da4-a94d-40108883b6be.png">

**Comment by udbyygyt** [comment]
是的。同样有之个问题

**Comment by xhacker5000** [comment]
把那个markdown去了就行了

**Comment by MIXPRODUCTIONMM** [comment]
![Uploading D1B570BA-67B6-4634-B088-55D9DE7E9FD3.jpeg…]()

**Comment by MIXPRODUCTIONMM** [comment]
https://weixin110.qq.com/s/35458c50e659

**Comment by MIXPRODUCTIONMM** [comment]
> https://weixin110.qq.com/s/35458c50e659

**Comment by MIXPRODUCTIONMM** [comment]
https://weixin110.qq.com/s/35458c50e659 1
Contact a WeChat user (by call, text, or other method outside WeChat) who meets the following conditions:
a. Signed up for WeChat at least 6 months ago
b. Has activated WeChat Pay
c. Hasn't completed "Help Friend Register" for other users in the past month
2
Ask the user to open WeChat, search for "WeChat Team", tap "Account", and select "Help Friend Register".

3
Ask the user to enter your mobile number.
+1 2099493419
